apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alertrule.yml

scrape_configs:
  - job_name: "federate"
    scrape_interval: 5s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="kube-state-metrics"}'
        - '{job="node-exporter"}'
        - '{job="nvidia-gpu-monitor"}'
    static_configs:
      - targets: [" {{ ip_address }}:{{ port }}"]
        labels:
          cluster: "{{ cluster name }}"
      - targets: [" {{ ip_address }}:{{ port }}"]
        labels:
          cluster: "{{ cluster_name }}"
      - targets: [" {{ ip_address }}:{{ port }}"]
        labels:
          cluster: "{{ cluster_name }}"

