apiVersion: v1
kind: ConfigMap
metadata:
  name: msteams-server-conf
  namespace: monitoring
data:
  config.yaml: |-
    connectors:
    - {{ receiver_name1 }}: {{ msteams_webhook_url_1 }}
    - {{ receiver_name2 }}: {{ msteams_webhook_url_2 }}
    - {{ receiver_name3 }}: {{ msteams_webhook_url_3 }}
