global:
  resolve_timeout: 5m

receivers:
- name: 'webhook'
  webhook_configs:
  - url: "http://prometheus-msteams:2000/alertmanager"
    send_resolved: true

route:
  group_by: ['job']
  group_wait: 10s
  group_interval: 5s
  repeat_interval: 2m
  receiver: 'webhook'
