{
 "title": "KubernetesMetrics",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{cluster=\"$cluster\"}, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Idle (total)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Idle (each)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", mode=\"idle\"}[1m])) by (kubernetes_pod_node_name)",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    },
    {}
   ]
  },
  {
   "title": "Load [rate 1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "Network receive bytes [rate 1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", device=~\"$network\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_node_name}} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_filesystem_avail_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", mountpoint=\"/\"}/node_filesystem_size_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", mountpoint=\"/\"}",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "Disk IO [rate 1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", device=~\"nvme0n1\"}[1m])",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "Network transmit bytes [rate 1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\", device=~\"$network\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_node_name }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"})/sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "description": "memory usage = memory total - memory free",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  }
 ]
}