{
 "title": "NVIDIAGPUExporter",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\"}, kubernetes_pod_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}/(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} + DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}))",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} + DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "GPU Memory Usage (Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} > 0",
     "legendFormat": "{{kubernetes_pod_node_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} > 0",
     "legendFormat": "{{kubernetes_pod_node_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg((DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}) > 100)"
    }
   ]
  },
  {
   "title": "GPU Power Usage (Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 3, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"}*10) > 1000",
     "legendFormat": "{{kubernetes_pod_node_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} > 50)"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", kubernetes_pod_node_name=~\"$node\"} > 40",
     "legendFormat": "{{kubernetes_pod_node_name}} - {{pod}}"
    }
   ]
  }
 ]
}