version: "3"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - {{ directory_to_prometheus.yml }}:/etc/prometheus/prometheus.yml
      - {{ directory_to_alert_rules.yml }}:/etc/prometheus/alert_rules.yml

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - {{ directory_to_alertmanager.yml }}:/etc/alertmanager.yml
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  

