global:
  scrape_interval:     1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['{{ ip_address }}:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['{{ ip_address }}:9100']
